from pathlib import Path
import json, zipfile, io, datetime, platform
import numpy as np, pandas as pd

def evidence_zip_bytes(tables, metadata, equations_md, references_md):
    bio=io.BytesIO()
    meta=dict(metadata)
    meta["generated_utc"]=datetime.datetime.now(datetime.timezone.utc).isoformat()
    meta["python"]=platform.python_version()
    with zipfile.ZipFile(bio,"w",zipfile.ZIP_DEFLATED) as z:
        for name,df in tables.items():
            z.writestr(f"tables/{name}.csv",df.to_csv(index=False))
        z.writestr("metadata.json",json.dumps(meta,indent=2,default=str))
        z.writestr("equations.md",equations_md)
        z.writestr("references.md",references_md)
        z.writestr("README.txt",
            "Paper-evidence bundle generated by Martensite Research Suite. "
            "Inspect metadata.json and equations.md before reporting results. "
            "A numerical result is evidence only for the declared inputs/model.")
    return bio.getvalue()
