from __future__ import annotations

from dataclasses import asdict, dataclass
import os
import platform
import sys
from typing import Iterable

import numpy as np

from .core import C_A_TO_M, C_M_TO_A
from .symbols import definitions_for_equation, operators_for_latex, symbol_rows

ENGINE_VERSION = "4.0.0-final"
BUILD_ID = "2026-08-31-final-notation-explicit"
BUILT_IN_TRANSFORMATION = "B2 austenite -> B19' martensite"
PRIMARY_SOURCE = {
    "title": "Compatibilities and supercompatibility conditions in shape memory alloys determined from correspondence, metrics and symmetries",
    "journal": "Acta Materialia",
    "volume": "316",
    "year": 2026,
    "article": "122399",
    "doi": "10.1016/j.actamat.2026.122399",
}


@dataclass(frozen=True)
class EquationRecord:
    key: str
    topic: str
    relation_latex: str
    source_location: str
    meaning: str
    provenance_class: str
    implementation: str
    scope: str
    caveat: str = ""


# Author names are intentionally not used as application branding.  Records are
# keyed to paper title/DOI + section/equation so outputs remain citable.
EQUATIONS: tuple[EquationRecord, ...] = (
    EquationRecord("PTMC-SC1", "Cofactor", r"\lambda_2=1", "Primary source Eq. (1), Sec. 1", "Middle principal stretch is unchanged; single-variant IPS compatibility condition.", "source equation", "src.ptmc.cofactor_conditions / stretch_from_metrics", "Classical PTMC/cofactor framework"),
    EquationRecord("PTMC-SC2", "Cofactor", r"a\cdot U\,\mathrm{cof}(U^2-I)n=0", "Primary source Eq. (2), Sec. 1", "Full cofactor equality for the selected rank-one twin/domain system.", "source equation", "src.ptmc.cofactor_conditions", "Use the paper normalization/convention for a,n; implementation also reports a scale-invariant normalized residual."),
    EquationRecord("PTMC-SC3", "Cofactor", r"\mathrm{tr}(U^2)-\det(U^2)-|a|^2|n|^2/4-2\ge0", "Primary source Eq. (3), Sec. 1", "Cofactor sufficiency inequality.", "source equation + scale-invariant implementation", "src.ptmc.cofactor_conditions", "Implementation writes |a|²|n|²/4 so arbitrary reciprocal scaling of the rank-one pair does not change the result; with unit n this reduces to the displayed paper convention."),
    EquationRecord("PTMC-V", "IPS geometry", r"v=(1-\lambda_1^2)^{-1/2}e_1\pm(\lambda_3^2-1)^{-1/2}e_3", "Primary source Eq. (4), Sec. 2.1", "Direction whose length is preserved by U when λ2=1.", "source equation", "src.equation_engine.ips_geometry_from_stretch", "Requires λ1≤1, λ2≈1, λ3≥1."),
    EquationRecord("PTMC-IPS", "IPS geometry", r"F=I+d\,m^T", "Primary source Eq. (5), Sec. 2.1", "Rank-one invariant-plane strain representation.", "source equation", "src.equation_engine.ips_geometry_from_stretch", "Displayed d,m are in the orthonormal PTMC frame."),
    EquationRecord("PTMC-TRACE", "IPS geometry", r"\lambda_1^2+\lambda_3^2+1=2+(1+\delta)^2+\tau^2", "Primary source Eq. (7), Sec. 2.1", "Trace invariant linking principal stretches to shear and dilatation.", "source equation", "src.equation_engine.stretch_shear_from_lambdas", "Assumes λ2=1."),
    EquationRecord("PTMC-DET", "IPS geometry", r"\lambda_1^2\lambda_3^2=(1+\delta)^2", "Primary source Eq. (8), Sec. 2.1", "Determinant/volume relation linking principal stretches and normal dilatation.", "source equation", "src.equation_engine.stretch_shear_from_lambdas", "Assumes λ2=1 and positive orientation."),
    EquationRecord("SHEAR-PHI", "Intercompatibility", r"\tan\phi=\delta/\tau_\perp", "Primary source Eq. (12), Sec. 2.2", "Angle between individual habit plane and twin mirror/junction plane.", "source equation", "src.equation_engine.shear_shear_geometry", "Scalar geometric relation."),
    EquationRecord("SHEAR-SHEAR-GEO", "Intercompatibility", r"a=2\cos\phi\,d", "Primary source Eq. (13), Sec. 2.2", "Geometric relation between IPS shear vector and twin shear vector.", "source equation", "src.equation_engine.shear_shear_geometry", "Assumes the supercompatible geometry of the derivation."),
    EquationRecord("LAMINATE-F", "Laminate", r"P=fF_1+(1-f)F_2=I+d\otimes(fm_A+(1-f)m_B)", "Primary source Eq. (14), Sec. 2.2", "If both variants share d, the average deformation stays IPS for every twin fraction f.", "source equation", "src.compatibility_methods.laminate_volume_fraction_scan", "Any-f consequence is tested numerically on a selected rank-one domain system."),
    EquationRecord("HC", "Correspondence group theory", r"H_C^A=G^A\cap C^{A\to M}G^M C^{M\to A}", "Primary source Eq. (26), Sec. 3.4", "Parent symmetries preserved by correspondence.", "source equation", "src.symmetry.correspondence_intersection_subgroup", "Built-in point groups: cubic parent, monoclinic 2/m daughter."),
    EquationRecord("LEFT-COSET", "Correspondence group theory", r"\{C^{A\to M_i}\}=g_i^A H_C^A C^{A\to M}", "Primary source Eq. (27), Sec. 3.4", "Correspondence variants are generated by left cosets.", "source equation", "src.equation_engine.correspondence_left_cosets", "Do not confuse with stretch variants, which are symmetry conjugates of U."),
    EquationRecord("N-CORR", "Correspondence group theory", r"N_C^M=|G^A|/|H_C^A|", "Primary source Eq. (28), Sec. 3.4", "Lagrange count of correspondence variants.", "source equation", "src.equation_engine.correspondence_left_cosets", "Built-in B2→B19' correspondence yields 12 variants."),
    EquationRecord("DOUBLE-COSET", "Correspondence group theory", r"O_k=H_C^A g_k^A H_C^A", "Primary source Sec. 3.5, around Eq. (30)", "Intercorrespondence classes reduce redundant variant-pair/twin calculations.", "source equation", "src.symmetry.double_cosets", "Class labels in software are implementation labels; do not assume a label-number identity with a printed table without checking representative symmetry."),
    EquationRecord("CMC", "Metric compatibility", r"CMC=(C^{M\to A})^T M_M C^{M\to A}-M_A", "Primary source Eq. (32), Sec. 4.1", "Difference of squared lengths after vs before correspondence.", "source equation", "src.core.cmc_matrix", "Generic metric/correspondence calculation."),
    EquationRecord("CMC-Q", "Metric compatibility", r"u_A^T CMC\,u_A=0", "Primary source Eq. (31), Sec. 4.1", "Zero set contains parent directions whose length is preserved by correspondence.", "source equation", "src.core.cmc_value", "A full compatible plane requires CMC quadratic degeneracy."),
    EquationRecord("G-CMC", "Metric compatibility", r"G_{CMC}=\{g^A\in G^A:\ q(g^Au)=0\ \forall u\in S_{CMC}\}", "Primary source Eq. (34), Sec. 4.1", "Parent symmetries preserving the CMC zero set.", "source equation", "src.equation_engine.cmc_symmetry_group", "Software reports zero-set proportionality and stricter exact-form residual separately."),
    EquationRecord("CMC-DEGEN", "Metric compatibility", r"q_i=0,\quad q_jq_k\le0", "Primary source Sec. 4.1 degeneracy criterion", "First-order CMC degeneracy gives one/two habit-plane factors; higher orders give a plane/full space.", "source equation", "src.core.cmc_degeneracy", "Tolerance is scale-aware and exported."),
    EquationRecord("SMC", "Metric shear", r"SMC=M_A^{-1}-C^{A\to M}M_M^{-1}(C^{A\to M})^T", "Primary source Eq. (41), Sec. 4.2", "Maps a compatible habit-plane covector to the IPS displacement/shear vector.", "source equation", "src.core.smc_matrix", "SMC is not CMC^{-1}."),
    EquationRecord("SMC-D", "Metric shear", r"d_A=SMC\,m_A", "Primary source Eq. (40), Sec. 4.2", "A→M IPS shear/displacement vector from the habit plane.", "source equation", "src.core.shear_direction_from_plane", "Plane scaling must be treated consistently; final epsilon uses normalized direct/reciprocal elements."),
    EquationRecord("SHEAR-SHEAR", "Metric intercompatibility", r"2(m_A^T n)d_A=a", "Primary source Sec. 4.2 shear/shear equation", "Links A/M habit-plane shear to the selected M/M twin shear.", "source equation", "src.core.shear_match", "Equation numbering is layout/OCR-sensitive in the available PDF; provenance stores section as well as relation."),
    EquationRecord("EPSILON", "Metric intercompatibility", r"\varepsilon=\|2(m_A^Tn)d_A-a\|/s", "Primary source Eq. (49), Sec. 5.2", "Normalized A/M–M/M shear mismatch; exact target is zero.", "source equation", "src.core.shear_match", "Dimensionless; requires consistent normalization of m_A,n,a."),
    EquationRecord("NITI-CMC", "Analytical B2/B19'", r"CMC/a_{B2}^2=\begin{pmatrix}(b^2+c^2)/4-1&(b^2-c^2)/4&-ac\cos\beta/2\\(b^2-c^2)/4&(b^2+c^2)/4-1&ac\cos\beta/2\\-ac\cos\beta/2&ac\cos\beta/2&a^2-1\end{pmatrix}", "Primary source Sec. 5.1", "Closed-form normalized CMC for the built-in B2→B19' correspondence.", "source equation", "src.equation_engine.niti_cmc_analytic", "a,b,c are normalized lattice ratios, not Å values."),
    EquationRecord("NITI-Q", "Analytical B2/B19'", r"q_1=(b^2-2)/2,\ q_{2,3}=(K\mp\sqrt\Delta)/4", "Primary source Sec. 5.1", "Closed-form CMC eigenspectrum with K=2a²+c²−4 and Δ=4a⁴+c⁴+4a²c²cos2β.", "source equation + algebraic verification", "src.equation_engine.niti_cmc_analytic", "Available PDF extraction/display is ambiguous for the q3 sign; software uses the + branch because it exactly reproduces the matrix eigenspectrum. This is explicitly documented, not silently changed."),
    EquationRecord("CT-C1", "Analytical B2/B19'", r"b=\sqrt2,\quad 2a^2+c^2-a^2c^2\sin^2\beta\ge2", "Primary source first-order CMC families, Sec. 5.1", "C1 A/M compatibility family.", "source equation", "src.equation_engine.first_order_families", "Dimensionless normalized ratios."),
    EquationRecord("CT-C2a", "Analytical B2/B19'", r"c^2=2(1-a^2)/(1-a^2\sin^2\beta),\ a\sin\beta\ge1,\ b\le\sqrt2", "Primary source first-order CMC families, Sec. 5.1", "C2a A/M compatibility family.", "source equation", "src.equation_engine.first_order_families", "Real-valued branch only."),
    EquationRecord("CT-C2b-EQ", "Analytical B2/B19'", r"a=1,\ \beta=90^\circ,\ b\le\sqrt2", "Primary source analytical C2b equation/derivation, Sec. 5.1", "C2b A/M compatibility family according to analytical equation and plotted example.", "source equation", "src.equation_engine.first_order_families", "A later source distance table prints b≥√2; both interpretations are exposed."),
    EquationRecord("CT-C2b-TABLE", "Analytical B2/B19'", r"a=1,\ \beta=90^\circ,\ b\ge\sqrt2", "Primary source later distance table", "Conflicting printed C2b inequality retained for source-audit purposes.", "source discrepancy", "src.equation_engine.first_order_families", "Do not use as the default analytical branch without reporting the discrepancy."),
    EquationRecord("CT-C3", "Analytical B2/B19'", r"c^2=2(1-a^2)/(1-a^2\sin^2\beta),\ a\le1,\ b\ge\sqrt2", "Primary source first-order CMC families, Sec. 5.1", "C3 A/M compatibility family.", "source equation", "src.equation_engine.first_order_families", "Real-valued branch only."),
    EquationRecord("CT-D1", "Higher degeneracy", r"b=\sqrt2,\ c^2=2(1-a^2)/(1-a^2\sin^2\beta)", "Primary source Appendix B Eq. (51)", "Second-order CMC degeneracy family D1.", "source equation", "src.equation_engine.higher_order_degeneracy_families", "Includes branch restriction a<1 or a≥1/sinβ and analytical plane."),
    EquationRecord("CT-D2", "Higher degeneracy", r"a=1,\ c=\sqrt2,\ \beta=90^\circ", "Primary source Appendix B Eq. (51)", "Second-order CMC degeneracy family D2.", "source equation", "src.equation_engine.higher_order_degeneracy_families", "Habit plane x+y=0."),
    EquationRecord("CT-E", "Higher degeneracy", r"a=1,\ b=c=\sqrt2,\ \beta=90^\circ", "Primary source Appendix B Eq. (52)", "Third-order degeneracy CMC=0; all directions preserve length.", "source equation", "src.equation_engine.higher_order_degeneracy_families", "Full-space metric correspondence."),
    EquationRecord("APP-C-O4", "Closed-form supercompatibility", r"a=a(\beta),\ c=c(\beta)\ \text{(Appendix C closed forms)}", "Primary source Appendix C", "One-dimensional O4 Type-I supercompatible metric family under C1 and the invariant [111]→[101] length condition.", "source equation", "src.equation_engine.appendix_c_o4", "Implementation keeps every square-root domain check explicit."),
    EquationRecord("FTC", "Transformation matrices", r"C^{M\to A}=T^{M\to A}F_A", "Primary source CT transformation-matrix framework, Sec. 3.2", "Relates correspondence, passive orientation and active distortion matrices.", "source equation", "src.equation_engine.ftc_from_C_and_F", "Matrix convention must be stated; export records the exact direction convention."),
    EquationRecord("TWIN-I", "Transformation twins", r"p_M=(C^{M\to A})^{-T}p_A,\quad s^2=\mathrm{tr}(C_{int}^T M_M C_{int}M_M^{-1})-3", "Primary source Sec. 3.3 Type-I construction", "Generic Type-I mirror plane is inherited by correspondence; the complementary shear element and amplitude use the daughter metric.", "source-derived implementation", "src.core.type_i_twin", "The UI also reports the exact parent symmetry element and intercorrespondence class used."),
    EquationRecord("TWIN-II", "Transformation twins", r"a_M=C^{M\to A}a_A,\quad s^2=\mathrm{tr}(C_{int}M_M^{-1}C_{int}^T M_M)-3", "Primary source Sec. 3.3 Type-II construction", "Generic Type-II shear/rotation direction is inherited by correspondence; the complementary plane and amplitude use the daughter metric.", "source-derived implementation", "src.core.type_ii_twin", "The UI also reports the exact parent symmetry element and intercorrespondence class used."),
    EquationRecord("APP-TEMP", "Temperature", r"\mathcal{R}(T)=\mathcal{R}[M_A(T),M_M(T),C]", "Software extension", "Re-evaluates the same crystallographic equations independently at every measured temperature row.", "software extension", "src.temperature.temperature_sweep", "No constitutive interpolation is implied unless the user supplies/interpolates input data."),
    EquationRecord("APP-MC", "Uncertainty", r"x^{(k)}\sim\mathcal{N}(\mu,\Sigma),\quad y^{(k)}=f(x^{(k)})", "Software extension", "Monte-Carlo propagation of reported lattice-parameter uncertainty through the deterministic crystallographic engine.", "software extension", "src.uncertainty.monte_carlo_uncertainty", "Distributional assumptions and random seed must be reported; probability labels are numerical uncertainty results, not theorem-level compatibility statements."),
    EquationRecord("APP-OPT", "Inverse design", r"\min_x\;J(x)\;\text{subject to user bounds/constraints}", "Software extension", "Numerical inverse search over lattice parameters using explicitly reported physical residuals/objectives.", "software extension", "src.design.inverse_lattice_design", "An optimizer finding a small residual does not prove that a chemical composition can realize the target lattice."),
    EquationRecord("APP-ML", "Composition to lattice ML", r"\hat y=f_\theta(x)\rightarrow\text{physics screen}(\hat y)", "Software extension", "Fits a data-driven composition→lattice model, then passes predicted lattices through the exact physics engine.", "software extension", "src.ml.train_lattice_model / physics_screen_predictions", "Prediction uncertainty and out-of-domain chemistry require independent validation; ML output is never labeled a crystallographic proof."),
    EquationRecord("IND-HADAMARD", "Independent interface compatibility", r"A-B=a\otimes m\quad\Longleftrightarrow\quad\mathrm{rank}(A-B)\le 1", "Independent classical interface-compatibility theorem", "Checks whether two deformation gradients can meet across a coherent planar interface by testing the singular spectrum of their jump.", "independent theorem implementation", "src.compatibility_methods.hadamard_rank_one_certificate", "A numerical rank-one residual certifies only the mathematical jump condition for the supplied matrices; physical interpretation depends on what A and B represent."),
    EquationRecord("IND-TWIN-SPECTRAL", "Independent twin compatibility", r"\chi_1\le1,\quad\chi_2=1,\quad\chi_3\ge1,\quad \chi=\mathrm{eig}(U_j^{-T}U_i^TU_iU_j^{-1})", "Independent Ball–James/Bhattacharya rank-one twin criterion; relation also summarized in Primary source Sec. 1", "Independent spectral test for whether a pair of stretch variants admits a rank-one twin relation.", "independent theorem implementation", "src.compatibility_methods.twin_rank_one_certificate", "This pairwise test is not identical to satisfying the full cofactor conditions for all laminate fractions."),
    EquationRecord("IND-LAMINATE", "Independent all-f verification", r"F(f)=U+f\,a\otimes n,\quad \sigma_2[F(f)]=1\;\forall f\in[0,1]", "Independent numerical consequence of full cofactor compatibility", "Directly scans the middle singular value of the laminate gradient over volume fraction.", "independent numerical verification", "src.compatibility_methods.laminate_volume_fraction_scan", "Finite sampling is a numerical verification over the chosen grid, not a symbolic proof for every real f."),
    EquationRecord("IND-TRIPLET-I", "Independent triplet condition", r"\alpha^2\gamma^2+2\gamma^2\beta^2-3\alpha^2\beta^2=0", "Independent cubic→orthorhombic triplet-condition branch", "Specialized TC-I residual for three-variant stress-free compatibility in the implemented transformation class.", "independent theorem implementation", "src.compatibility_methods.triplet_condition_orthorhombic", "Transformation-class specific; not a B2→B19' monoclinic certification criterion."),
    EquationRecord("IND-TRIPLET-II", "Independent triplet condition", r"2\alpha^2+\beta^2-3\gamma^2=0", "Independent cubic→orthorhombic triplet-condition branch", "Specialized TC-II residual for three-variant stress-free compatibility in the implemented transformation class.", "independent theorem implementation", "src.compatibility_methods.triplet_condition_orthorhombic", "Transformation-class specific; not a B2→B19' monoclinic certification criterion."),
    EquationRecord("APP-RECON", "Parent reconstruction", r"g_P\;\xrightarrow{OR,\;variant}\;g_D", "Independent crystallographic extension", "Reconstructs parent orientations from daughter orientations by OR-variant consistency using several transparent algorithmic families.", "independent method extension", "src.reconstruction", "Synthetic benchmark performance is not a substitute for validation on experimental EBSD with known parent ground truth."),
)


def equation_registry() -> dict[str, EquationRecord]:
    return {r.key: r for r in EQUATIONS}


def equations_for(keys: Iterable[str]) -> list[dict[str, object]]:
    """Return equation provenance plus an explicit symbol/notation dictionary.

    The symbol list is intentionally part of exported provenance so a manuscript
    record remains readable without relying on the Streamlit UI or implicit
    crystallographic notation.
    """
    reg = equation_registry()
    out: list[dict[str, object]] = []
    for k in keys:
        if k not in reg:
            continue
        row: dict[str, object] = asdict(reg[k])
        row["symbols"] = symbol_rows(definitions_for_equation(k))
        row["operators"] = symbol_rows(operators_for_latex(reg[k].relation_latex))
        out.append(row)
    return out


def method_provenance(cc1_tol: float, cc2_tol: float) -> dict[str, object]:
    """Machine-readable method metadata for result exports."""
    return {
        "engine_version": ENGINE_VERSION,
        "build_id": BUILD_ID,
        "git_commit_if_available": os.getenv("GITHUB_SHA") or os.getenv("COMMIT_SHA"),
        "python": sys.version.split()[0],
        "platform": platform.platform(),
        "numpy": np.__version__,
        "primary_source": PRIMARY_SOURCE,
        "built_in_transformation": BUILT_IN_TRANSFORMATION,
        "correspondence_A_to_M": np.asarray(C_A_TO_M, float).tolist(),
        "correspondence_M_to_A": np.asarray(C_M_TO_A, float).tolist(),
        "numerical_tolerances": {
            "cc1_abs_lambda2_minus_1": float(cc1_tol),
            "cc2_normalized": float(cc2_tol),
        },
        "scientific_separation": {
            "austenite_martensite": "lambda2 and CMC degeneracy",
            "classical_supercompatibility": "CC1-CC3 for classified Type-I, Type-II and Compound domains",
            "metric_intercompatibility": "CMC habit plane + SMC shear + twin shear/shear epsilon",
        },
        "source_discrepancies": [
            "C2b inequality: analytical equation/plotted example imply b<=sqrt(2); later distance table prints b>=sqrt(2). Both are exposed; analytical equation is the default compatibility branch.",
            "Closed-form q3 display/extraction is ambiguous in the available source rendering. The implementation uses (K+sqrt(Delta))/4 because it is algebraically required and is verified against the numerical eigenspectrum of the printed CMC matrix.",
            "Table-2 C2a/C3 equality: the printed numerical value 0.269706 is reproduced by the linear ratio distance |c-c_target|, whereas the visually/parsed squared expression gives a different value. Both are exported explicitly.",
        ],
    }
